platform :ios,'9.0'
use_frameworks!  
source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'KRNetworking' do
    xcodeproj 'KRNetworking'
    pod 'Alamofire'
end
